name: DockerTest
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime # replace with the Docker image you want to use
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

